name: nutrient_flutter_web
description: Web implementation of the nutrient_flutter plugin.
version: 1.0.0
homepage: https://nutrient.io/
repository: https://github.com/PSPDFKit/pspdfkit-flutter
issue_tracker: https://support.nutrient.io/hc/en-us/requests/new
documentation: https://nutrient.io/guides/flutter/

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  nutrient_flutter_platform_interface: ^1.0.0
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    implements: nutrient_flutter_bindings
    platforms:
      web:
        pluginClass: NutrientFlutterWeb
        fileName: src/nutrient_flutter_web.dart

dependency_overrides:
  nutrient_flutter_platform_interface:
    path: ../nutrient_flutter_platform_interface
