#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/kato/fvm/versions/3.44.6"
export "FLUTTER_APPLICATION_PATH=/Users/kato/Documents/Projects/nutrient/PSPDFKit/flutter/nutrient_flutter/catalog"
export "FLUTTER_FRAMEWORK_SWIFT_PACKAGE_PATH=/Users/kato/Documents/Projects/nutrient/PSPDFKit/flutter/nutrient_flutter/catalog/ios/Flutter/ephemeral/Packages/.packages/FlutterFramework"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=/Users/kato/Documents/Projects/nutrient/PSPDFKit/flutter/nutrient_flutter/catalog/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NUMBER=1"
export "DART_DEFINES=RkxVVFRFUl9WRVJTSU9OPTMuNDQuNg==,RkxVVFRFUl9DSEFOTkVMPXN0YWJsZQ==,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049ZWU4MGYwOGJiZg==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049ODM2NzVlZDI3Ng==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My4xMi4y"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/kato/Documents/Projects/nutrient/PSPDFKit/flutter/nutrient_flutter/catalog/.dart_tool/package_config.json"
