name: nutrient_flutter_android
description: Android implementation of the nutrient_flutter plugin.
version: 1.0.0
homepage: https://nutrient.io/
repository: https://github.com/PSPDFKit/pspdfkit-flutter
issue_tracker: https://support.nutrient.io/hc/en-us/requests/new
documentation: https://nutrient.io/guides/flutter/

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  nutrient_flutter_platform_interface: ^1.0.0
  jni: ^0.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  jnigen: ^0.14.2

flutter:
  plugin:
    implements: nutrient_flutter_bindings
    platforms:
      android:
        package: com.nutrient.nutrient_flutter_android
        pluginClass: NutrientFlutterPlugin
        dartPluginClass: NutrientFlutterAndroid

dependency_overrides:
  nutrient_flutter_platform_interface:
    path: ../nutrient_flutter_platform_interface
