///
///  Copyright © 2024-2026 PSPDFKit GmbH. All rights reserved.
///
///  THIS SOURCE CODE AND ANY ACCOMPANYING DOCUMENTATION ARE PROTECTED BY INTERNATIONAL COPYRIGHT LAW
///  AND MAY NOT BE RESOLD OR REDISTRIBUTED. USAGE IS BOUND TO THE PSPDFKIT LICENSE AGREEMENT.
///  UNAUTHORIZED REPRODUCTION OR DISTRIBUTION IS SUBJECT TO CIVIL AND CRIMINAL PENALTIES.
///  This notice may not be removed from this file.
///

/// Bookmark models and utilities for the Nutrient Flutter SDK.
///
/// The [Bookmark] class is generated by Pigeon and represents a PDF bookmark.
/// Use [BookmarkExtensions] for convenience methods like [pageIndex] and [toInstantJson].
/// Use [BookmarkFactory] for creating bookmarks easily.
///
/// Example:
/// ```dart
/// import 'package:nutrient_flutter/nutrient_flutter.dart';
///
/// // Create a bookmark for page 5
/// final bookmark = BookmarkFactory.forPage(pageIndex: 5, name: 'Important Section');
/// await document.addBookmark(bookmark);
///
/// // Get all bookmarks and check their pages
/// final bookmarks = await document.getBookmarks();
/// for (final bookmark in bookmarks) {
///   print('${bookmark.name}: Page ${bookmark.pageIndex}');
/// }
/// ```
library bookmarks;

export 'bookmark_extensions.dart';
